#!/usr/bin/env python3
"""Copy the Bézier handle helpers of darktable's drawn path and brush shapes, unchanged, from
darktable's src/develop/masks/path.c and brush.c into omalux/native/engine/shape_nodes_port.inc
(see shape_nodes.inc): the angle and scale of a path node's handles (kept while one handle is
dragged), a brush node's feather handle and the position on a brush segment. They are static
in darktable; _update_bezier_ctrl_points itself is exported by libdarktable. Re-run after
updating the darktable submodule:

    python3 development/tools/darktable/extract_mask_nodes.py
"""
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[3]
MASKS = ROOT / 'darktable/src/develop/masks'
TARGET = ROOT / 'omalux/native/engine/shape_nodes_port.inc'
# (file, first line starts with, block ends before the line that starts with)
BLOCKS = [
    ('path.c', 'float angle_2d(', 'void _update_bezier_ctrl_points('),
    ('brush.c', 'static void _brush_get_XY(', 'static void _brush_border_get_XY('),
    ('brush.c', 'static void _brush_ctrl2_to_feather(', 'static void _brush_catmull_to_bezier('),
    ('brush.c', 'static float _brush_get_position_in_segment(', 'static int _brush_events_mouse_scrolled('),
]


def main():
    out = ['// Generated by development/tools/darktable/extract_mask_nodes.py from darktable '
           'src/develop/masks.\n// Do not edit; see shape_nodes.inc.\n']
    for name, first, after in BLOCKS:
        lines = (MASKS / name).read_text().splitlines(keepends=True)
        try:
            start = next(i for i, l in enumerate(lines) if l.startswith(first))
            end = next(i for i, l in enumerate(lines) if i > start and l.startswith(after))
        except StopIteration:
            sys.exit(f'extract_mask_nodes: block {first!r} not found in {name}')
        # keep the "static inline" line and the doc comment above a function
        while start > 0 and (lines[start - 1].startswith('static') or lines[start - 1].strip().startswith(('/**', '*', '*/'))):
            start -= 1
        # drop the trailing doc comment that belongs to the next function
        while end > start and lines[end - 1].strip().startswith(('/**', '*', '*/')):
            end -= 1
        out.append(f'\n// ---- {name} lines {start + 1}-{end} ----\n')
        out.append(''.join(lines[start:end]))
    TARGET.write_text(''.join(out))
    print(f'wrote {TARGET.relative_to(ROOT)}')


if __name__ == '__main__':
    main()
