#!/usr/bin/env python3
"""Copy color calibration's colour checker solver out of darktable's src/iop/channelmixerrgb.c,
unchanged, into omalux/native/engine/checker_port.inc (see checker.c).

The patch extraction, the illuminant and matrix solver and the validation are static functions
of the module that read their state from the GUI data passed to them; checker.c passes its own
stand-in. Re-run after updating the darktable submodule:

    python3 development/tools/darktable/extract_checker.py
"""
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[3]
SOURCE = ROOT / 'darktable/src/iop/channelmixerrgb.c'
TARGET = ROOT / 'omalux/native/engine/checker_port.inc'
BLOCKS = [
    ('typedef enum dt_solving_strategy_t', 'typedef enum dt_spot_mode_t'),
    ('static void _check_if_close_to_daylight(', 'static void _set_trouble_messages('),
]


def main():
    lines = SOURCE.read_text().splitlines(keepends=True)
    out = ['// Generated by development/tools/darktable/extract_checker.py from darktable '
           'src/iop/channelmixerrgb.c.\n// Do not edit; see checker.c.\n']
    for first, after in BLOCKS:
        try:
            start = next(i for i, l in enumerate(lines) if l.startswith(first))
            end = next(i for i, l in enumerate(lines) if i > start and l.startswith(after))
        except StopIteration:
            sys.exit(f'extract_checker: block {first!r} not found')
        out.append(f'\n// ---- channelmixerrgb.c lines {start + 1}-{end} ----\n')
        out.append(''.join(lines[start:end]))
    TARGET.write_text(''.join(out))
    print(f'wrote {TARGET.relative_to(ROOT)}')


if __name__ == '__main__':
    main()
