#!/usr/bin/env python3
"""Copy darktable's perspective-fitting code out of src/iop/ashift.c, unchanged except for
the few GUI calls headless code cannot make, into omalux/native/engine/ashift_fit_port.inc.

rotate and perspective's line detection, outlier removal, Nelder-Mead fit and automatic crop
are static functions of the module; ashift_fit.c includes this extract and drives it the way
the module's buttons do. Re-run after updating the darktable submodule:

    python3 development/tools/darktable/extract_ashift_fit.py
"""
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[3]
SOURCE = ROOT / 'darktable/src/iop/ashift.c'
TARGET = ROOT / 'omalux/native/engine/ashift_fit_port.inc'
TYPES = ROOT / 'omalux/native/engine/ashift_fit_types.inc'

# (first line marker, marker of the line after the block); markers are the start of a line
BLOCKS = [
    ('#define ROTATION_RANGE ', '// For line detection we use the LSD'),
    ('typedef enum dt_iop_ashift_method_t', 'typedef struct dt_iop_ashift_gui_data_t'),
    ('// normalized product of two 3x1 vectors', '// check if module parameters are set to all neutral'),
    ('static void rgb2grey256(', '// manually adjust crop area by shifting its center'),
    ('// determine if the line is vertical or horizontal', 'static void _gui_update_structure_states('),
]
# GUI-only calls inside the copied functions: (pattern, replacement, reason)
EDITS = [
    (r'^\s*dt_iop_gui_(enter|leave)_critical_section\(self\);\n', '',
     'the GUI lock; headless the fit runs on the engine worker alone'),
    (r'^\s*dt_bauhaus_combobox_set\(g->cropmode, p->cropmode\);\n', '',
     'the "automatic cropping" combobox; the parameter itself is set'),
    (r'^\s*dt_control_queue_redraw_center\(\);\n', '', 'redraw of the darkroom centre view'),
]


def main():
    text = SOURCE.read_text()
    lines = text.splitlines(keepends=True)
    out = ['// Generated by development/tools/darktable/extract_ashift_fit.py from darktable '
           'src/iop/ashift.c.\n// Do not edit; see ashift_fit.c.\n']
    for first, after in BLOCKS:
        start = next(i for i, l in enumerate(lines) if l.startswith(first))
        end = next(i for i, l in enumerate(lines) if i > start and l.startswith(after))
        block = ''.join(lines[start:end])
        out.append(f'\n// ---- ashift.c lines {start + 1}-{end} ----\n')
        out.append(block)
        if first.startswith('#define ROTATION_RANGE'):
            # ashift.c includes the line segment detector and the simplex here (lines 101, 105)
            out.append('#include "iop/ashift_lsd.c"\n#include "iop/ashift_nmsimplex.c"\n')
    result = ''.join(out)
    for pattern, replacement, _ in EDITS:
        result, count = re.subn(pattern, replacement, result, flags=re.M)
        if not count:
            sys.exit(f'extract_ashift_fit: pattern not found: {pattern}')
    # the definitions and types first (ashift_fit_types.inc), then the functions: ashift_fit.c
    # declares its stand-in for the GUI data between the two.
    split = result.index('\n// ---- ashift.c lines', result.index('typedef enum dt_iop_ashift_method_t'))
    types, functions = result[:split] + '\n', out[0] + result[split:]
    TYPES.write_text(types)
    TARGET.write_text(functions)
    for path, part in ((TYPES, types), (TARGET, functions)):
        print(f'wrote {path.relative_to(ROOT)} ({part.count(chr(10))} lines)')


if __name__ == '__main__':
    main()
