use crate::{
    develop::{CpuImage, RgbaPixel},
    io::{
        EncodeError, EncodeOptions, EncodeWorkingSetProfile, JpegMetadataFootprint, MetadataBundle,
        OutputFormat, OutputProfile, ResourceLimits, SignalRelation,
        color::{ColorError, WorkingToSrgbTransform, srgb_profile},
    },
};

use super::{
    EncodeCancellation, MetadataWriteReport,
    metadata::{materialize_metadata, plan_metadata},
};

// Canonical sizes generated by the supported LCMS 2.x profile constructors.
// Tests fail closed if a dependency change alters either serialized profile.
const CANONICAL_SRGB_ICC_BYTES: u64 = 588;
const CANONICAL_LINEAR_REC2020_ICC_BYTES: u64 = 568;

pub struct JpegEncodeInput<'a> {
    pub image: &'a CpuImage,
    pub signal_relation: SignalRelation,
    pub metadata: &'a MetadataBundle,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PreparedDisplayRgb {
    pub width: u32,
    pub height: u32,
    pub rgb8: Vec<u8>,
    pub icc: Vec<u8>,
    pub icc_provenance: crate::io::IccProfileProvenance,
    pub clipped_samples: u64,
    pub alpha_flattened_pixels: u64,
    pub exif: Option<Vec<u8>>,
    pub metadata_report: MetadataWriteReport,
}

/// Produces deterministic encoded-sRGB bytes without invoking an image codec.
pub fn prepare_display_rgb8(
    input: JpegEncodeInput<'_>,
    options: &EncodeOptions,
    limits: &ResourceLimits,
    cancellation: &EncodeCancellation,
) -> Result<PreparedDisplayRgb, EncodeError> {
    // This semantic gate deliberately precedes all allocations and metadata
    // work. RAW requires the separate scene-to-display renderer.
    if input.signal_relation == SignalRelation::SceneRelatedRaw {
        return Err(EncodeError::SceneToDisplayRenderingRequired);
    }
    if cancellation.cancelled() {
        return Err(EncodeError::Cancelled);
    }
    options.validate()?;
    if options.format != OutputFormat::Jpeg {
        return Err(EncodeError::UnsupportedFormat);
    }
    if options.profile != OutputProfile::Srgb {
        return Err(EncodeError::UnsupportedProfile);
    }
    input.image.validate().map_err(|_| EncodeError::Encode)?;
    let (width, height) = (input.image.width(), input.image.height());
    if width > u16::MAX.into() || height > u16::MAX.into() {
        return Err(EncodeError::InvalidOptions);
    }
    limits
        .preflight_encode_dimensions(width, height)
        .map_err(EncodeError::Limit)?;

    // The first pass is allocation-free: it records at most the fixed
    // allowlist and computes the exact rebuilt TIFF size.
    let metadata_plan = plan_metadata(input.metadata, options.metadata, limits, &|| {
        cancellation.cancelled()
    })?;
    let input_metadata_bytes = [
        input.metadata.exif(),
        input.metadata.xmp(),
        input.metadata.iptc(),
    ]
    .into_iter()
    .flatten()
    .try_fold(0_u64, |total, value| total.checked_add(value.len() as u64))
    .ok_or(EncodeError::Limit(
        crate::io::LimitError::ArithmeticOverflow,
    ))?;
    let transform_profile_bytes = CANONICAL_SRGB_ICC_BYTES
        .checked_add(CANONICAL_LINEAR_REC2020_ICC_BYTES)
        .ok_or(EncodeError::Limit(
            crate::io::LimitError::ArithmeticOverflow,
        ))?;
    let estimate = limits
        .estimate_encode_working_set(
            width,
            height,
            EncodeWorkingSetProfile::JpegRgb8,
            JpegMetadataFootprint {
                input_metadata_bytes,
                output_exif_bytes: metadata_plan.output_bytes(),
                output_icc_bytes: CANONICAL_SRGB_ICC_BYTES,
                transform_profile_bytes,
            },
        )
        .map_err(EncodeError::Limit)?;

    preflight_alpha(input.image, options, cancellation)?;
    let sanitized =
        materialize_metadata(input.metadata, metadata_plan, &|| cancellation.cancelled())?;
    let profile = srgb_profile(limits).map_err(map_color)?;
    let icc_provenance = profile.icc_provenance();
    if icc_provenance.bytes != CANONICAL_SRGB_ICC_BYTES {
        return Err(EncodeError::ColorManagement);
    }
    let icc = profile.to_icc(limits).map_err(map_color)?;
    drop(profile);
    let working_profile = crate::io::color::linear_rec2020_profile(limits).map_err(map_color)?;
    if working_profile.icc_provenance().bytes != CANONICAL_LINEAR_REC2020_ICC_BYTES {
        return Err(EncodeError::ColorManagement);
    }
    drop(working_profile);
    let rgb_len = usize::try_from(estimate.encoded_rgb_bytes)
        .map_err(|_| EncodeError::Limit(crate::io::LimitError::ArithmeticOverflow))?;
    let mut rgb8 = Vec::new();
    rgb8.try_reserve_exact(rgb_len)
        .map_err(|_| EncodeError::Limit(crate::io::LimitError::Allocation))?;

    let row_width = usize::try_from(width)
        .map_err(|_| EncodeError::Limit(crate::io::LimitError::ArithmeticOverflow))?;
    let transform = WorkingToSrgbTransform::new(limits).map_err(map_color)?;
    let mut destination_row = Vec::new();
    destination_row
        .try_reserve_exact(row_width)
        .map_err(|_| EncodeError::Limit(crate::io::LimitError::Allocation))?;
    destination_row.resize(row_width, [0.0_f32; 4]);
    let mut flattened_row = Vec::new();
    if matches!(options.alpha, crate::io::AlphaPolicy::Flatten(_)) {
        flattened_row
            .try_reserve_exact(row_width)
            .map_err(|_| EncodeError::Limit(crate::io::LimitError::Allocation))?;
    }
    let mut clipped_samples = 0_u64;
    let mut alpha_flattened_pixels = 0_u64;
    for source_row in input.image.pixels().chunks_exact(row_width) {
        if cancellation.cancelled() {
            return Err(EncodeError::Cancelled);
        }
        let transformed_source = match options.alpha {
            crate::io::AlphaPolicy::Reject => source_row,
            crate::io::AlphaPolicy::Flatten(background) => {
                flattened_row.clear();
                for pixel in source_row {
                    if pixel.alpha() != 1.0 {
                        alpha_flattened_pixels =
                            alpha_flattened_pixels
                                .checked_add(1)
                                .ok_or(EncodeError::Limit(
                                    crate::io::LimitError::ArithmeticOverflow,
                                ))?;
                    }
                    flattened_row.push(flatten(pixel, background)?);
                }
                &flattened_row
            }
        };
        let report = transform
            .transform_scanline(
                transformed_source,
                &mut destination_row,
                input.signal_relation,
                options.range,
                limits,
            )
            .map_err(map_color)?;
        clipped_samples =
            clipped_samples
                .checked_add(report.clipped_samples)
                .ok_or(EncodeError::Limit(
                    crate::io::LimitError::ArithmeticOverflow,
                ))?;
        for pixel in &destination_row {
            rgb8.extend(pixel[..3].iter().map(|sample| quantize_u8(*sample)));
        }
    }
    debug_assert_eq!(rgb8.len(), rgb_len);
    if cancellation.cancelled() {
        return Err(EncodeError::Cancelled);
    }
    Ok(PreparedDisplayRgb {
        width,
        height,
        rgb8,
        icc,
        icc_provenance,
        clipped_samples,
        alpha_flattened_pixels,
        exif: sanitized.exif,
        metadata_report: sanitized.report,
    })
}

fn preflight_alpha(
    image: &CpuImage,
    options: &EncodeOptions,
    cancellation: &EncodeCancellation,
) -> Result<(), EncodeError> {
    if !matches!(options.alpha, crate::io::AlphaPolicy::Reject) {
        return Ok(());
    }
    let width = usize::try_from(image.width()).map_err(|_| EncodeError::InvalidOptions)?;
    for (row, pixels) in image.pixels().chunks_exact(width).enumerate() {
        if cancellation.cancelled() {
            return Err(EncodeError::Cancelled);
        }
        if let Some(column) = pixels.iter().position(|pixel| pixel.alpha() != 1.0) {
            let pixel = row
                .checked_mul(width)
                .and_then(|value| value.checked_add(column))
                .and_then(|value| u64::try_from(value).ok())
                .ok_or(EncodeError::InvalidOptions)?;
            return Err(EncodeError::AlphaPresent { pixel });
        }
    }
    Ok(())
}

fn flatten(pixel: &RgbaPixel, background: [f32; 3]) -> Result<RgbaPixel, EncodeError> {
    let alpha = f64::from(pixel.alpha());
    let inverse = 1.0 - alpha;
    let values = [pixel.red(), pixel.green(), pixel.blue()].map(f64::from);
    let mut output = [0.0_f32; 3];
    for index in 0..3 {
        let value = values[index] * alpha + f64::from(background[index]) * inverse;
        if !value.is_finite() || value > f64::from(f32::MAX) || value < f64::from(f32::MIN) {
            return Err(EncodeError::ColorManagement);
        }
        output[index] = value as f32;
    }
    RgbaPixel::new(output[0], output[1], output[2], 1.0).map_err(|_| EncodeError::ColorManagement)
}

fn quantize_u8(sample: f32) -> u8 {
    debug_assert!((0.0..=1.0).contains(&sample));
    (f64::from(sample) * 255.0 + 0.5).floor() as u8
}

fn map_color(error: ColorError) -> EncodeError {
    match error {
        ColorError::Limit(error) => EncodeError::Limit(error),
        ColorError::OutputOutOfRange { .. } => EncodeError::OutOfRange,
        ColorError::SceneToDisplayRenderingRequired => EncodeError::SceneToDisplayRenderingRequired,
        _ => EncodeError::ColorManagement,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{
        develop::RgbaPixel,
        io::{AlphaPolicy, MetadataPolicy, SdrRangePolicy},
    };

    #[test]
    fn generated_profile_sizes_pin_the_preflight_contract() {
        let limits = ResourceLimits::default();
        assert_eq!(
            srgb_profile(&limits).unwrap().icc_provenance().bytes,
            CANONICAL_SRGB_ICC_BYTES
        );
        assert_eq!(
            crate::io::color::linear_rec2020_profile(&limits)
                .unwrap()
                .icc_provenance()
                .bytes,
            CANONICAL_LINEAR_REC2020_ICC_BYTES
        );
    }

    #[test]
    fn non_power_of_two_peak_accepts_exactly_and_rejects_one_below() {
        let source = CpuImage::new(
            13,
            7,
            vec![RgbaPixel::new(0.18, 0.18, 0.18, 1.0).unwrap(); 91],
        )
        .unwrap();
        let mut exif = vec![0_u8; 26];
        exif[..8].copy_from_slice(b"II*\0\x08\0\0\0");
        exif[8..10].copy_from_slice(&1_u16.to_le_bytes());
        exif[10..12].copy_from_slice(&0x8827_u16.to_le_bytes());
        exif[12..14].copy_from_slice(&3_u16.to_le_bytes());
        exif[14..18].copy_from_slice(&1_u32.to_le_bytes());
        exif[18..20].copy_from_slice(&400_u16.to_le_bytes());
        let metadata =
            MetadataBundle::try_new(Some(exif), None, None, true, &ResourceLimits::default())
                .unwrap();
        let plan = plan_metadata(
            &metadata,
            crate::io::MetadataPolicy::StripLocation,
            &ResourceLimits::default(),
            &|| false,
        )
        .unwrap();
        assert_eq!(plan.output_bytes(), 44);
        let baseline = ResourceLimits::default()
            .estimate_encode_working_set(
                13,
                7,
                EncodeWorkingSetProfile::JpegRgb8,
                JpegMetadataFootprint {
                    input_metadata_bytes: 26,
                    output_exif_bytes: 44,
                    output_icc_bytes: CANONICAL_SRGB_ICC_BYTES,
                    transform_profile_bytes: CANONICAL_SRGB_ICC_BYTES
                        + CANONICAL_LINEAR_REC2020_ICC_BYTES,
                },
            )
            .unwrap();
        assert_eq!(baseline.codec_metadata_scratch_bytes, 618);
        let input = || JpegEncodeInput {
            image: &source,
            signal_relation: SignalRelation::LinearizedDisplayReferred,
            metadata: &metadata,
        };
        assert!(
            prepare_display_rgb8(
                input(),
                &EncodeOptions::default(),
                &ResourceLimits::default().with_max_working_bytes(baseline.peak_bytes),
                &EncodeCancellation::default(),
            )
            .is_ok()
        );
        assert!(matches!(
            prepare_display_rgb8(
                input(),
                &EncodeOptions::default(),
                &ResourceLimits::default().with_max_working_bytes(baseline.peak_bytes - 1),
                &EncodeCancellation::default(),
            ),
            Err(EncodeError::Limit(crate::io::LimitError::WorkingBytes {
                requested,
                maximum
            })) if requested == baseline.peak_bytes && maximum + 1 == requested
        ));

        // A one-pixel image with retained EXIF is deliberately codec-dominant:
        // the encoder copies plus its co-resident JFIF/ICC segment exceed all
        // preparation scratch. This pins the other branch of `max()`.
        let tiny =
            CpuImage::new(1, 1, vec![RgbaPixel::new(0.18, 0.18, 0.18, 1.0).unwrap()]).unwrap();
        let codec_dominant = ResourceLimits::default()
            .estimate_encode_working_set(
                1,
                1,
                EncodeWorkingSetProfile::JpegRgb8,
                JpegMetadataFootprint {
                    input_metadata_bytes: 26,
                    output_exif_bytes: 44,
                    output_icc_bytes: CANONICAL_SRGB_ICC_BYTES,
                    transform_profile_bytes: CANONICAL_SRGB_ICC_BYTES
                        + CANONICAL_LINEAR_REC2020_ICC_BYTES,
                },
            )
            .unwrap();
        assert!(codec_dominant.codec_peak_bytes > codec_dominant.preparation_peak_bytes);
        let tiny_input = || JpegEncodeInput {
            image: &tiny,
            signal_relation: SignalRelation::LinearizedDisplayReferred,
            metadata: &metadata,
        };
        assert!(
            prepare_display_rgb8(
                tiny_input(),
                &EncodeOptions::default(),
                &ResourceLimits::default().with_max_working_bytes(codec_dominant.codec_peak_bytes),
                &EncodeCancellation::default(),
            )
            .is_ok()
        );
        assert!(matches!(
            prepare_display_rgb8(
                tiny_input(),
                &EncodeOptions::default(),
                &ResourceLimits::default()
                    .with_max_working_bytes(codec_dominant.codec_peak_bytes - 1),
                &EncodeCancellation::default(),
            ),
            Err(EncodeError::Limit(crate::io::LimitError::WorkingBytes {
                requested,
                maximum
            })) if requested == codec_dominant.codec_peak_bytes && maximum + 1 == requested
        ));
    }

    fn image(pixels: &[[f32; 4]]) -> CpuImage {
        CpuImage::new(
            u32::try_from(pixels.len()).unwrap(),
            1,
            pixels
                .iter()
                .map(|value| RgbaPixel::new(value[0], value[1], value[2], value[3]).unwrap())
                .collect(),
        )
        .unwrap()
    }

    fn prepare(
        image: &CpuImage,
        options: &EncodeOptions,
    ) -> Result<PreparedDisplayRgb, EncodeError> {
        prepare_display_rgb8(
            JpegEncodeInput {
                image,
                signal_relation: SignalRelation::LinearizedDisplayReferred,
                metadata: &MetadataBundle::default(),
            },
            options,
            &ResourceLimits::default(),
            &EncodeCancellation::default(),
        )
    }

    #[test]
    fn neutral_quantization_has_exact_goldens() {
        let source = image(&[
            [0.0, 0.0, 0.0, 1.0],
            [0.18, 0.18, 0.18, 1.0],
            [1.0, 1.0, 1.0, 1.0],
        ]);
        let first = prepare(&source, &EncodeOptions::default()).unwrap();
        let second = prepare(&source, &EncodeOptions::default()).unwrap();
        assert_eq!(first.rgb8, [0, 0, 0, 118, 118, 118, 255, 255, 255]);
        assert_eq!(first, second);
    }

    #[test]
    fn scene_related_is_rejected_before_other_options() {
        let source = image(&[[0.0, 0.0, 0.0, 0.5]]);
        let cancellation = EncodeCancellation::default();
        cancellation.cancel();
        let error = prepare_display_rgb8(
            JpegEncodeInput {
                image: &source,
                signal_relation: SignalRelation::SceneRelatedRaw,
                metadata: &MetadataBundle::default(),
            },
            &EncodeOptions::default(),
            &ResourceLimits::default(),
            &cancellation,
        )
        .unwrap_err();
        assert!(matches!(
            error,
            EncodeError::SceneToDisplayRenderingRequired
        ));
    }

    #[test]
    fn alpha_reject_and_linear_flatten_are_explicit() {
        let source = image(&[[0.8, 0.2, 0.1, 0.5]]);
        assert!(matches!(
            prepare(&source, &EncodeOptions::default()),
            Err(EncodeError::AlphaPresent { pixel: 0 })
        ));
        let options = EncodeOptions {
            alpha: AlphaPolicy::Flatten([0.2, 0.2, 0.2]),
            ..Default::default()
        };
        let flattened = prepare(&source, &options).unwrap();
        let expected = image(&[[0.5, 0.2, 0.15, 1.0]]);
        assert_eq!(
            flattened.rgb8,
            prepare(&expected, &EncodeOptions::default()).unwrap().rgb8
        );
        assert_eq!(flattened.alpha_flattened_pixels, 1);
    }

    #[test]
    fn range_reject_and_clip_are_reported() {
        let source = image(&[[4.0, -1.0, 0.5, 1.0]]);
        let reject = EncodeOptions {
            range: SdrRangePolicy::Reject,
            ..Default::default()
        };
        assert!(matches!(
            prepare(&source, &reject),
            Err(EncodeError::OutOfRange)
        ));
        let clipped = prepare(&source, &EncodeOptions::default()).unwrap();
        assert!(clipped.clipped_samples > 0);
    }

    #[test]
    fn cancellation_and_unsupported_contracts_are_loud() {
        let source = image(&[[0.2, 0.2, 0.2, 1.0]]);
        let cancellation = EncodeCancellation::default();
        cancellation.cancel();
        assert!(matches!(
            prepare_display_rgb8(
                JpegEncodeInput {
                    image: &source,
                    signal_relation: SignalRelation::LinearizedDisplayReferred,
                    metadata: &MetadataBundle::default(),
                },
                &EncodeOptions::default(),
                &ResourceLimits::default(),
                &cancellation,
            ),
            Err(EncodeError::Cancelled)
        ));
        let heic = EncodeOptions {
            format: OutputFormat::Heic,
            metadata: MetadataPolicy::StripAll,
            ..Default::default()
        };
        assert!(matches!(
            prepare(&source, &heic),
            Err(EncodeError::UnsupportedFormat)
        ));
    }
}
